PARTS=[
dict(pn='RK-A-101',name='Upright',qty=4,kind='tube',L=1950,A=40,t=1.6,mass='3.65 kg',
 mat_short='GI SHS 40×40×1.6',mat='Pre-galvanised steel hollow section 40 × 40 × 1.6 mm to IS 4923, grade YST210 minimum, Z275 coating',
 holes=dict(dia=9,pitch=50,start=150,count=36,faces=2),
 fn='Carries the whole rack. Also carries the 50 mm accessory grid, which is the interface every other module bolts to.',
 desc="The upright is the only part in the rack that is genuinely critical, and it is critical for two unrelated reasons. Structurally it is barely working — compressive stress is 2.3 MPa against a 210 MPa yield, and the Euler buckling margin is over a thousand. It is sized at 40 × 40 × 1.6 for dent resistance and for the feel of the product, not for load. What it really does is carry the accessory grid: 36 holes at 50 mm pitch on two adjacent faces, through both walls, in line. Every beam, deck, LED rail, sensor bracket and panel in the system locates off those holes. Get the grid wrong and nothing else in the rack fits.",
 mfg=["Cut from 6 m stock, four uprights per rack. Cut all four for a given rack from the same bar batch so any mill tolerance is common to the set.",
      "Punch or laser the Ø9 grid. <b>Dimension every hole cumulatively from the foot end</b>, never hole-to-hole — a 0.2 mm incremental error repeated 36 times is 7 mm at the top and the four uprights stop accepting a common beam.",
      "Both faces are punched in one setup where the press allows, to keep the two grids square to each other.",
      "Deburr both sides of every hole. A burr on the inside of the tube is invisible and holds water.",
      "Zinc-rich touch-up on both sawn ends, then press a plastic cap into each end. This is what makes mill-finish GI acceptable in a humid room.",
      "If powder coating: mask the grid holes or ream them after coating. A coated Ø9 will not take an M8 cleanly."],
 qc=["Cumulative hole position ±0.2 mm over any 400 mm — check all four uprights, every rack",
     "Ø9.0 go / Ø9.3 no-go gauge on a 10% sample of holes","Both ends capped and touched up","Length 1950 ±1.0 mm"]),

dict(pn='RK-A-102',name='Beam, long',qty=10,kind='tube',L=1176,A=30,t=1.5,mass='1.58 kg',
 mat_short='GI SHS 30×30×1.5',mat='Pre-galvanised steel hollow section 30 × 30 × 1.5 mm to IS 4923, grade YST210 minimum',
 holes=dict(dia=9,pitch=50,start=25,count=4,faces=1),
 fn='Spans the rack width and carries the deck. Eight at tier level, two in the base frame.',
 desc="The beam sets the bed flatness, which is the specification that makes flood-and-drain work at all. At the 80 kg design load it deflects 1.79 mm and in normal service 0.50 mm, both inside the 3 mm limit — and that limit exists because a sagging bed gives a different flood depth at the centre trays than at the ends. The section was reduced from 40 × 40 to 30 × 30 during cost reduction after the check showed 40 × 40 was oversized by four times; 30 × 30 × 1.5 still carries a 1.68× margin on the flatness criterion. Bending stress is 37 MPa against 210 MPa yield.",
 mfg=["Ten per rack: eight tier beams, two base-frame beams. Nest with RK-A-103 on the same bar to hold waste under 10%.",
      "Two Ø9 holes per end on one face, at 25 mm and 75 mm from the end face, on the section centreline.",
      "Square cut. Length tolerance ±1.0 mm — the beam sets the rack width, and four beams of different lengths will rack the frame out of square.",
      "Deburr, touch up both cut ends with zinc-rich paint.",
      "Do not flame cut galvanised section; cold saw or bandsaw only."],
 qc=["Length 1176 ±1.0 mm, measured on every piece","End hole position ±0.3 mm from the end face","Squareness of cut ±0.5°"]),

dict(pn='RK-A-103',name='Beam, short (base)',qty=2,kind='tube',L=480,A=30,t=1.5,mass='0.64 kg',
 mat_short='GI SHS 30×30×1.5',mat='Pre-galvanised steel hollow section 30 × 30 × 1.5 mm to IS 4923',
 holes=dict(dia=9,pitch=50,start=25,count=4,faces=1),
 fn='Ties front to rear uprights at the base frame, in the depth plane.',
 desc="Only two of these, and only at the base. The per-tier cross beams were deliberately deleted during cost reduction on the grounds that each deck assembly already ties front to rear through its own edge frame — building a second tie in steel underneath it was duplication. What remains is this pair at the base plus the rear X-brace, and that combination is the one open structural question in the design. It is scheduled to be closed by acceptance test T16, the depth-plane sway test — 200 N at the top bed, deflection ≤ 10 mm with no permanent set. If P3 fails, the fix is to reinstate per-tier cross beams at about ₹562 a rack; nothing else changes.",
 mfg=["Two per rack. Cut from the offcut of the RK-A-102 bar — nesting 4 × 1176 with 2 × 480 leaves only 336 mm waste on a 6 m length.",
      "Same end-hole pattern as RK-A-102: two Ø9 at 25 and 75 from each end face.",
      "Deburr and touch up cut ends."],
 qc=["Length 480 ±1.0 mm","End hole position ±0.3 mm"]),

dict(pn='RK-A-104',name='Rear X-brace',qty=2,kind='plate',L=1797,W=25,t=3,mass='1.06 kg ea',
 mat_short='GI flat 25×3',mat='Pre-galvanised steel flat bar 25 × 3 mm',
 holes=dict(dia=9,pos=[(20,12.5),(1777,12.5)]),
 fn='The only diagonal in the rack. Resists side-sway in both the front and rear planes.',
 desc="Two of these cross in the rear plane. They exist because deleting the per-tier cross beams left the frame with no diagonal anywhere, and the front plane cannot have one — it has to stay open for tray access. So the rear brace carries side-sway for both planes, through the decks. It costs about ₹210 of flat bar and it is not optional. A rear panel would be a stiffer diaphragm, and the design deliberately does not use it that way: the panel comes off for cleaning, and structure must never depend on a part somebody removes to wash.<br><br><b>Rev 2 correction.</b> Rev 1 dimensioned this part at 1345 mm. Reconciling the drawing against the released model showed the brace spans a 1195 × 1342 mm opening, whose true diagonal is 1797 mm — Rev 1 would have produced a brace 452 mm short, which is not a part that can be fitted at all. The model governs; the length is 1797.",
 mfg=["Two per rack, fitted as a crossing pair on the rear face at Y 560–563, between the deck rear edge and the plenum face.",
      "<b>Check the length against the opening before cutting a batch.</b> 1797 is the diagonal of a 1195 × 1342 frame; if the frame is built to a different squareness the diagonal changes.",
      "Shear or laser from flat bar. One Ø9 hole at each end, 20 mm from the end, on the centreline.",
      "The brace is fitted <b>after</b> the frame is squared and <b>before</b> final torque — it locks in whatever squareness it finds.",
      "Deburr all four edges. This part is at hand height at the rear of the rack.",
      "Touch up sheared edges with zinc-rich paint."],
 qc=["Length 1797 ±1.5 mm — check against the model, not against Rev 1","Hole centres 1757 ±1.0 mm apart","Fitted length across the diagonal 1797, over a 1195 × 1342 opening","No sharp sheared edge"]),

dict(pn='RK-A-105',name='Levelling foot',qty=4,kind='plate',L=50,W=50,t=15,mass='0.16 kg',
 mat_short='M12 adj. foot, nylon base',mat='Bought-out M12 × 60 adjustable levelling foot, nylon or PP base, ±20 mm adjustment',
 fn='Levels the rack. Levelness is functional here, not cosmetic.',
 desc="A purchased item — the drawing is an installation envelope, not a manufacturing drawing. It matters more than a foot usually does, because flood-and-drain needs the beds level: an out-of-level bed gives an uneven flood depth across the four tray positions and the outer trays crop differently from the inner ones. Specify ±20 mm of adjustment so the rack can be levelled on a floor laid to drain, which by definition is not flat. A nylon or PP base rather than bare steel, because it sits on a wet floor.",
 mfg=["Purchased. Confirm the thread engages the upright base or a welded/riveted M12 nut plate.",
      "Fit a locknut so the setting cannot walk under vibration from the tier fans.",
      "Set-up: level across the width and the depth at the lowest tier, then re-check after loading the first tier."],
 qc=["±20 mm adjustment range available","Locknut fitted and tight","Bed level ≤ 1 mm/m in both axes after setting"]),

dict(pn='RK-A-106',name='Wall anchor bracket',qty=2,kind='plate',L=60,W=60,t=4,mass='0.15 kg',
 mat_short='GI plate 4 mm',mat='Pre-galvanised steel sheet 4 mm, bent to 90°',
 holes=dict(dia=9,pos=[(15,30),(45,30)]),
 fn='Anchors the rack to the wall. Fitted item, not an option.',
 desc="This part exists because the validation found the rack tips. An empty rack goes over under a 139 N horizontal pull at the top bed — about 14 kg, which anyone yanking a stuck tray will exceed without meaning to. Loaded it takes 307 N. Height-to-depth is 3.48:1, below the 4:1 ratio at which anchoring is normally mandated, so a freestanding rack is defensible on paper; the empty case is not. Two brackets, four bolts, and the problem disappears. If a rack genuinely must stand free, the top tier is to be left unloaded and the rack labelled to say so.",
 mfg=["Two per rack. Laser cut from 4 mm GI sheet, bend to 90° ±0.5°.",
      "Two Ø9 holes in the rack leg matching the 50 mm grid pitch. Slot the wall leg (9 × 20) so the bracket tolerates masonry anchor position error.",
      "Deburr and touch up the cut and bent edges — bending cracks the zinc on the outside of the radius.",
      "Supply with M8 masonry anchors, minimum 60 mm embedment, sized for the substrate.",
      "<b>Back-to-back variant.</b> In the room layout, rows B and C are bolted rear to rear through this same bracket rather than to a wall. For those racks the wall leg is bolted to the partner rack's bracket with M8 through-bolts and the slot is not used — supply the bracket unslotted, or slot it and fit a penny washer."],
 qc=["Bend angle 90° ±0.5°","Hole pitch 50 ±0.3 mm","Zinc touch-up present on the bend radius"]),

dict(pn='RK-A-107',name='Beam-end L-bracket',qty=12,kind='plate',L=50,W=50,t=3,mass='0.07 kg',
 mat_short='GI plate 3 mm',mat='Pre-galvanised steel sheet 3 mm, bent to 90°',
 holes=dict(dia=9,pos=[(12,15),(12,38),(38,25)]),
 fn='Connects beam ends to the upright grid.',
 desc="The bracket that carries every beam-to-upright joint, twelve per rack. Each one takes a 196 N beam reaction through two M8 bolts, giving a shear safety factor of 157 and a bearing factor of 108 on the 1.6 mm upright wall — enormously over-strength, because the governing constraint is the bolt and hole geometry, not the load. This is also the part that disappears first at volume: a formed keyhole beam-end engaging a slot in the upright deletes all twelve brackets and 48 fasteners, and turns assembly from bolting into dropping a beam in and tapping it down.",
 mfg=["Twelve per rack. Nest with RK-A-106 on the same 3–4 mm sheet.",
      "Laser cut, bend to 90° ±0.5°. Two Ø9 in the upright leg at 50 mm grid pitch, one Ø9 in the beam leg.",
      "Deburr thoroughly — these are handled repeatedly during assembly.",
      "Touch up the bend radius.",
      "<b>Volume note:</b> this part is a candidate for deletion at 100+ units. Do not invest in tooling for it."],
 qc=["Bend 90° ±0.5°","Upright-leg hole pitch 50 ±0.3 mm","Flat within 0.5 mm"]),

dict(pn='RK-A-201',name='Deck rail, long',qty=8,kind='tube',L=1176,A=25,t=1.5,mass='1.30 kg',
 mat_short='GI SHS 25×25×1.5',mat='Pre-galvanised steel hollow section 25 × 25 × 1.5 mm to IS 4923',
 holes=dict(dia=9,pitch=50,start=25,count=4,faces=1),
 fn='Front and rear members of the deck frame. Two per tier.',
 desc="Part of the deck sub-assembly rather than the frame, and the distinction matters: the deck is the constant, and what sits on it — flood table, capillary tray, drained shelf, deep bed, NFT channel, or nothing at all for germination — is the variable. That is what makes one rack serve microgreens, aquatic propagation and germination without redesign. The deck rails also do a structural job the frame no longer does: with the per-tier cross beams deleted, the deck's own edge frame is what ties the front beam to the rear beam.",
 mfg=["Eight per rack, two per tier. Nest with RK-A-202 on the same 25 × 25 bar.",
      "Two Ø9 per end on one face at 25 and 75 mm.",
      "Length tolerance ±1.0 mm — the deck must drop into the frame without forcing.",
      "Deburr and touch up cut ends."],
 qc=["Length 1176 ±1.0 mm","Deck assembly drops into the frame without force"]),

dict(pn='RK-A-202',name='Deck rail, cross',qty=16,kind='tube',L=510,A=25,t=1.5,mass='0.56 kg',
 mat_short='GI SHS 25×25×1.5',mat='Pre-galvanised steel hollow section 25 × 25 × 1.5 mm to IS 4923',
 holes=dict(dia=9,pitch=50,start=25,count=2,faces=1),
 fn='Intermediate deck supports, four per tier, running front to back.',
 desc="Four per tier, dividing the deck into three bays so the expanded mesh does not sag under a flooded tray. They also make the deck a rigid frame in its own right, which is what allows it to act as the horizontal tie between front and rear beams. Sixteen pieces per rack makes this the highest-count fabricated part in the design, and 32 of the rack's 208 fasteners are here — which is why a tabbed end that slots into the long rail without a bolt is on the volume roadmap.",
 mfg=["Sixteen per rack. Highest quantity part — set up a stop on the saw rather than measuring each piece.",
      "One Ø9 per end on one face at 25 mm.",
      "Deburr and touch up cut ends.",
      "<b>Volume note:</b> a tabbed end slotting into RK-A-201 removes 32 fasteners per rack. Worth tooling with the keyhole beam-end."],
 qc=["Length 510 ±1.0 mm — sample 20% once the saw stop is set, 100% on the first batch","Deburr on both ends"]),

dict(pn='RK-A-203',name='Deck mesh panel',qty=4,kind='plate',L=1176,W=560,t=1.6,mass='1.98 kg',
 mat_short='GI expanded mesh 1.6',mat='Galvanised expanded metal, 1.6 mm strand, ≥ 70% open area, in a folded edge',perf=True,
 fn='The tray support surface. Its top face is the bed datum.',
 desc="Straight from commercial greenhouse benching practice, where hot-dip galvanised expanded metal decking is the standard because roughly 76% open area drains freely and passes air without obstructing the tier. The one rule a fabricator must not break is here: <b>the mesh top face is the bed datum</b>. Every vertical dimension in the rack is measured from it — the deck rail and beam hang below it, the tray, canopy and LED are measured up from it. Build the deck to the datum, not to the beam. <b>Rev 2 correction.</b> The model briefly carried this part at a 35% open-area density, which put it at 5.37 kg and the whole rack at 126.2 kg. Expanded mesh at the specified ≥70% open area is 1.98 kg, and the model density has been corrected to 1884 kg/m³ to match. Rack dry mass is <b>112.7 kg</b>. Where a drawing and the model disagree the model normally governs — this is the one case where the drawing was right.",
 mfg=["Four per rack. Shear from expanded mesh sheet, then fold a 20 mm edge on all four sides for stiffness and to remove the sharp expanded edge.",
      "Rivet into the deck frame with 32 × 4.8 mm stainless blind rivets, eight per panel.",
      "<b>Set the mesh top face flush with the deck frame top face, ≤ 1 mm step.</b> This face is the bed datum for the whole rack.",
      "Expanded mesh has a grain direction — lay the long way of the diamond along the 1176 mm span so the strands work in their stiff axis.",
      "Handle with gloves until the edge is folded."],
 qc=["Mesh top face flush with frame, ≤ 1 mm step","No sharp edge reachable by hand","Open area ≥ 70% on the supplied material certificate","Panel sits flat in the frame with no rock"]),

dict(pn='RK-A-301',name='LED mounting rail',qty=8,kind='tube',L=1176,A=20,t=1.5,mass='0.35 kg',
 mat_short='Al 6061-T6 SHS 20×20×1.5',mat='Aluminium 6061-T6 hollow section 20 × 20 × 1.5 mm, mill or clear anodised',
 holes=dict(dia=9,pitch=50,start=25,count=4,faces=1),
 fn='Carries the LED fixtures. Two per tier, bolted to the underside of the tier above.',
 desc="Aluminium rather than steel, and that is a deliberate exception. It is the one visible premium cue on an otherwise galvanised rack, it is light enough to handle one-handed at height, and it does not need coating. It sits at the underside of the tier above rather than having its own supports — the first attempt gave each tier a dedicated rail and it clashed with the structure above by 4 mm, because a 400 mm pitch will not carry tray, crop, clearance, fixture and a separate rail. Fixtures hang beneath on adjustable hangers, so LED height is trimmed continuously by the hanger while the rail itself sits on the discrete 50 mm grid. Deflection with a 2 kg fixture is 0.93 mm.",
 mfg=["Eight per rack. Cut from 6 m aluminium stock; nest across three racks to hold waste near 6%.",
      "Two Ø9 per end. Drill, do not punch — thin-wall aluminium tears on a punch without support.",
      "Deburr. Aluminium burrs are sharp and this part is handled overhead.",
      "No coating required. If anodising, clear only — do not colour-match to the steel, the contrast is the point.",
      "Keep aluminium tooling separate from steel to avoid embedding iron particles, which will corrode as rust spots."],
 qc=["Length 1176 ±1.0 mm","Fixture mounts without forcing","No sharp edge — handled overhead"]),

dict(pn='RK-A-401',name='Flood tray (wet module)',qty=4,kind='tray',L=1176,W=560,H=47,t=3,flood=22,drain=40,drain_x=60,boss_y=480,ovf_x=120,ovf_dia=32,collar_h=30,mass='2.31 kg',
 mat_short='HDPE 3 mm, food grade',mat='HDPE sheet 3 mm, food-contact grade, natural or white, with documented resin traceability',
 fn='Holds the flood. The only part of the rack the crop touches.',
 desc="The wet module, and the only structural part in the rack that must be food-contact grade — which is the whole reason the frame does not have to be. Separating the wet zone from the structure is what allowed galvanised steel elsewhere and took roughly a third out of the cost. It floods to 22 mm, holds 14.5 L, and dwells ten minutes; the rim at 47 mm leaves 16.5 L of freeboard, which is what contains a blocked-drain fault long enough for the solenoid to close. Specify it in <b>white</b>: the underside of the tray above then becomes the canopy reflector for the tier below, at no cost.<br><br><b>Rev 2 — three features became tooling dimensions.</b> The overflow is no longer a loose standpipe but a <b>30 mm collar moulded into the tray floor</b>, which eliminated the failure mode of somebody not refitting it after cleaning. Both penetrations moved off the tray centreline into the rack's wet-services corridor: the drain boss sits <b>60 mm from the right end and 480 mm from the front edge</b>, the overflow collar <b>120 mm from the right end on the same centreline</b>, 60 mm apart. Those three numbers are now form-tool geometry, not site drilling, and they must match the rack's drain header spacing across all four trays.",
 mfg=["Four per rack. <b>Thermoforming is the correct process</b> at 1176 × 560 — tooling is a single aluminium or resin form, roughly ₹30–80k, and it takes the part from about ₹1,228 fabricated to under ₹700.",
      "Injection moulding is <b>not</b> viable at this size for a first production run — it needs a very large press and a tool costing several lakh.",
      "If fabricated from sheet for the prototype: weld corners inside and out, then radius all internal corners so they can be wiped clean.",
      "<b>Ø40 drain boss at 60 mm from the right end and 480 mm from the front edge</b> — on the wet-services centreline, <i>not</i> on the tray centreline. The boss must be the low point: form a fall of 2–3 mm toward it across the tray floor.",
      "<b>Ø32 overflow collar at 120 mm from the right end, same 480 mm centreline</b>, 60 mm from the drain boss. Crest height 30 mm above the tray floor, formed as part of the tool. The crest sets the flood depth mechanically — it is not adjustable and must not be.",
      "Both penetrations take a PP tank connector with the EPDM washer on the wet face. Bore the collar after forming so the crest edge is clean and square.",
      "<b>Flood test every tray to the rim for 30 minutes before it leaves the shop.</b> A leak found in the workshop costs nothing; the same leak found on a loaded rack costs a crop.",
      "Food-contact resin with traceability documentation retained per batch — this is the one material clause that is not negotiable."],
 qc=["30 minute flood test to rim, zero leakage, 100% of trays","Fall toward the drain 2–3 mm, no ponding away from the boss",
     "Collar crest 30 +0/−1 mm above the tray floor, measured at four points around the crest",
     "Boss centres 60 ±1.0 mm apart, and 480 ±1.0 mm from the front edge on all four trays of a rack","Internal corners radiused, wipe-clean, no crevice","Resin certificate on file per batch","Colour white for the reflector function"]),

dict(pn='RK-A-501',name='Reflective panel, rear',qty=4,kind='plate',L=1176,W=343,t=2,mass='0.77 kg',
 mat_short='White PP 2 mm, matte',mat='White polypropylene sheet 2 mm, matte finish, ≥ 85% diffuse reflectance',perf=True,
 holes=dict(dia=6.5,pos=[(40,25),(1136,25),(40,318),(1136,318)]),
 fn='Rear enclosure. Doubles as the plenum face, so it distributes air and reflects light.',
 desc="One part doing two jobs. As a reflector it recovers edge spill — geometry puts roughly 14% of each bar's flux outside the 560 mm bed depth, of which a matte white surface returns an estimated 8–12% to the canopy, mostly at the outer tray positions where uniformity is worst. As the plenum face, perforated, it is what lets air enter along the whole 1176 mm rather than from one end, which is the difference between about 33% and 10% velocity variation across the bed. Fitted outboard of the X-brace at Y 563–565, so it is <b>not structural</b> and comes off for cleaning without touching the frame. Matte, never mylar — specular surfaces make bright spots and worsen uniformity.",
 mfg=["Four per rack, one per tier, fitted outboard of the rear brace.",
      "Shear to size. Four Ø6.5 mounting holes on the 50 mm grid pitch.",
      "Perforate the face for plenum air. Hole size and open area to be set at commissioning against the measured canopy velocity — start at 4 mm holes on a 25 mm grid and open up if velocity is short.",
      "Matte face outward toward the canopy. Do not substitute mylar, foil or gloss.",
      "Do not overtighten the M6 fixings — polypropylene creeps. Penny washers, 6 N·m."],
 qc=["Diffuse reflectance ≥ 85% on the supplied material data","Matte face fitted inward","Panel removable by hand tools only, no frame disturbance","Perforation pattern consistent panel to panel"]),

dict(pn='RK-A-502',name='Reflective panel, side',qty=8,kind='plate',L=563,W=343,t=2,mass='0.37 kg',
 mat_short='White PP 2 mm, matte',mat='White polypropylene sheet 2 mm, matte finish, ≥ 85% diffuse reflectance',
 holes=dict(dia=6.5,pos=[(30,25),(533,25),(30,318),(533,318)]),
 fn='Side enclosure. Closes the tier so plenum air passes through the canopy instead of around it.',
 desc="Eight per rack, two per tier, on the inboard faces of the uprights. The airflow argument is the stronger one: an open rack lets plenum air short-circuit around the canopy rather than through it, and the side panels are what turn each tier into a duct and make the 0.2–0.5 m/s canopy target achievable rather than aspirational. The light recovery is a bonus. The front stays deliberately open for access — a roll-down curtain is the option if full enclosure is ever wanted. Like the rear panel, non-structural by design.",
 mfg=["Eight per rack. Shear to size, four Ø6.5 mounting holes.",
      "Not perforated — only the rear panel is the plenum face.",
      "Matte face inward toward the canopy.",
      "Break all four edges. These are at hand height when loading trays.",
      "M6 with penny washers, 6 N·m. Polypropylene creeps under load."],
 qc=["Reflectance ≥ 85%","Edges broken, no sharp edge at hand height","Removable without disturbing the frame"]),
]
